In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)

In [5]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [10]:
df["Designation"] = ["Doctor", "Engineer", "PornStar", "Techer"]

In [11]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000    PornStar
3  Linda   42    London   85000      Techer

In [19]:
df.drop(['City', 'Salary'], axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [20]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [25]:
#Selecting Subsets of Rows and Columnsabs
df.loc[[0,1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [26]:
df.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [27]:
#Conditonal Selection
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
#I only want to see whoes age is above 30 

df[df["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [30]:
#i only want to see people whoes age is above 30 and their city must be paPermissionError

df[(df["Age"] > 30) & (df["City"] ==  'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000